# Generated by Django 4.2.7 on 2023-11-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="Order",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
    ]
