# Generated by Django 4.2.7 on 2023-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.TextField(null=True),
        ),
    ]
