# Generated by Django 4.2.7 on 2023-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.TextField(),
        ),
    ]
