# Generated by Django 4.2.7 on 2023-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="demo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
