# Generated by Django 4.2.7 on 2023-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_demo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
