# Generated by Django 4.2.7 on 2023-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_productrating_downloads_productrating_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrating",
            name="downloads",
        ),
        migrations.RemoveField(
            model_name="productrating",
            name="file",
        ),
        migrations.AddField(
            model_name="product",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="file",
            field=models.FileField(null=True, upload_to="product_files/"),
        ),
    ]
