# Generated by Django 4.2.7 on 2023-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="customer_imgs/"),
        ),
    ]
