# Generated by Django 4.2.7 on 2024-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_customer_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="product_imgs/"),
        ),
    ]
